paths:
  input: data/
  output: results/
  trimmed: trimmed_data/
  aligned: aligned_data/
  marked_duplicates: marked_duplicates/

sra_accessions:
  - SRR20458000
  - SRR20755928
  - SRR21031366

trimmomatic:
  adapter_file: TruSeq3-PE-2.fa
  leading: 3
  trailing: 3
  slidingwindow: 4:15
  minlen: 36

bowtie2:
  index: /references/hg38.fasta

picard:
  remove_duplicates: true
  jvm_opts: "-Xmx60g -XX:ParallelGCThreads=4"

